import numpy as np
import os
import netCDF4 as nc
import sys

sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))
import interp_utilities as  iutil

import tarfile
import xhycom

# Consolidate u,v surface currents from global RTOFS into a single NetCDF file.

dirin=sys.argv[1]
PDYCC=sys.argv[2]
flout=sys.argv[3]
print(PDYCC)
PDY=PDYCC[0:8]
CYC=PDYCC[8:10]
print(PDY)
print(CYC)

# *.archs.a.tgz

#tgzfiles = os.listdir(dirin)
tgzfiles = [f for f in os.listdir(dirin) if f.endswith('.a.tgz')]

tgzfiles[3]='rtofs_glo.t00z.n-24.archs.a.tgz'
tgzfiles[4]='rtofs_glo.t00z.n-07.archs.a.tgz'
tgzfiles[5]='rtofs_glo.t00z.n00.archs.a.tgz'
print(tgzfiles)
nt=len(tgzfiles)



nt=7


k=0    
flin=dirin+"/"+tgzfiles[k]

#data=nc.Dataset(flin,"r")
#X=data["Longitude"][:,:]
#Y=data["Latitude"][:,:]
#fill_value0=data["u_velocity"]._FillValue
fltemplate="/mnt/sda/keston/rtofs_cice/rtofs.20260622/rtofs_glo_2ds_f009_prog.nc"
data = nc.Dataset(fltemplate,"r")
X=data["Longitude"]
Y=data["Latitude"]

nx=X.shape[0]
ny=X.shape[1]

U=np.zeros((nt,1,nx,ny))
V=np.zeros((nt,1,nx,ny))

time=np.zeros(nt)
print(U.shape)
for k in range(nt):
    flin=dirin+"/"+tgzfiles[k]
    with tarfile.open(flin, "r:gz") as tar:
        tar.extractall(path=dirin)
    ds = xhycom.open_dataset(flin[0:-4])
    U0=ds["u-vel."]
    V0=ds["v-vel."]
    print(k)
    U[k,0,:,:]=U0[:,:]
    V[k,0,:,:]=V0[:,:]
    tmp=iutil.FileNameToUnixTime(flin,PDY,CYC)
    time[k]=tmp
    print(flin)
    print(time[k])

tindx = np.argsort(time)
time=time[tindx]
U=U[tindx,:,:,:]
V=V[tindx,:,:,:]

Layers=data["Layer"][:]

with nc.Dataset(flout, 'w', format='NETCDF4') as ncout:

    ncout.createDimension('Layer' , 1)  
    ncout.createDimension('X' , nx)
    ncout.createDimension('Y' , ny)
    ncout.createDimension('time', nt)

    lon_var=ncout.createVariable('longitude', 'f4', ('X','Y'))
    var=data["Longitude"]
    iutil.CopyAttributes(var, lon_var)
    lon_var[:,:]=X[:,:]

    lat_var=ncout.createVariable('latitude', 'f4', ('X','Y'))
    var=data["Latitude"]
    iutil.CopyAttributes(var, lat_var)
    lat_var[:,:]=Y[:,:]
    
    time_var=ncout.createVariable('time', 'f8', ('time',))
    time_var.units         = 'seconds since 1970-01-01 00:00:00.0 0:00'
    time_var.long_name     = 'verification time generated by wgrib2 function verftime()'
    time_var.standard_name = 'time'
    time_var.axis          = 'T'
    time_var[:] = time[:]
    
    #u_var               = ncout.createVariable('u-vel', 'f4', ('time','Layer','X','Y'),fill_value    = fill_value0)
    u_var               = ncout.createVariable('u-vel', 'f4', ('time','Layer','X','Y'))
    var=data["u_velocity"]
    iutil.CopyAttributes(var, u_var)
    u_var[:,:,:,:]      = U

#    v_var               = ncout.createVariable('v-vel', 'f4', ('time','Layer','X','Y'),fill_value    = fill_value0)
    v_var               = ncout.createVariable('v-vel', 'f4', ('time','Layer','X','Y'))
    var=data["v_velocity"]
    iutil.CopyAttributes(var, v_var)
    v_var[:,:,:,:]      = V
    
    l_var           = ncout.createVariable('Layer', 'i4', ('Layer',))
    var=data["Layer"]
    iutil.CopyAttributes(var, l_var)
    l_var[:] = Layers[0]
