import numpy as np
import os
import netCDF4 as nc
import sys

import datetime
import re

def get_rtofs_unix_time(file_path: str) -> int:
    """
    Extracts the valid UTC Unix timestamp from a NOAA RTOFS file path.
    Example path: '/pub/data/nccf/com/rtofs/prod/rtofs.20260813/rtofs_glo.t12z.f024.archv.nc'
    """
    # Regex to find 8-digit date, cycle hour (tXXz), and forecast hour (fXXX)
    match = re.search(r'rtofs\.(\d{8}).*?\.t(\d{2})z\.f(\d{3})', file_path)
    
    if not match:
        raise ValueError("Could not parse RTOFS naming convention from path.")
        
    date_str, cycle_str, forecast_str = match.groups()
    
    # 1. Parse base model initialization time to a UTC datetime object
    base_time_str = f"{date_str} {cycle_str}"
    base_dt = datetime.datetime.strptime(base_time_str, "%Y%m%d %H").replace(tzinfo=datetime.timezone.utc)
    
    # 2. Add the forecast hour offset
    forecast_hours = int(forecast_str)
    valid_dt = base_dt + datetime.timedelta(hours=forecast_hours)
    
    # 3. Convert valid UTC datetime to epoch integer
    return int(valid_dt.timestamp())

# --- Example Usage ---
sample_path = "/pub/data/nccf/com/rtofs/prod/rtofs.20260813/rtofs_glo.t12z.f024.archv.nc"
unix_time = get_rtofs_unix_time(sample_path)

print(f"Unix Timestamp: {unix_time}")
# Output: 1786708800 (Reflects: 2026-08-14 12:00:00 UTC)

#Consolidate RTOFS ice forecast files to a single NetCDF file.

# Get the path relative to this file and add to sys.path
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))
import interp_utilities as  iutil

dirin=sys.argv[1]
PDYCC=sys.argv[2]
flout=sys.argv[3]
print(PDYCC)
PDY=PDYCC[0:8]
CYC=PDYCC[8:10]
print(PDY)
print(CYC)


ncfiles = os.listdir(dirin)
print(ncfiles)
nt=len(ncfiles)

nt=17


k=0
flin=dirin+"/"+ncfiles[k]
data=nc.Dataset(flin,"r")
X=data["Longitude"][:,:]
Y=data["Latitude"][:,:]
fill_value0=data["ice_coverage"]._FillValue
nx=X.shape[0]
ny=X.shape[1]
F=np.zeros((nt,nx,ny),dtype=np.float32)
MT=np.zeros(nt)
time=np.zeros(nt)
print("nx = "+str(nx))
print("ny = "+str(ny))
print(F.shape)
for k in range(nt):
    flin=dirin+"/"+ncfiles[k]
    data=nc.Dataset(flin,"r")
    F0=data["ice_coverage"][:]
    print(F0.shape)
    print(F.shape)
    print(str(k)+" of "+ str(nt))
    F[k,:,:]=F0[0,:,:]
    tmp=iutil.FileNameToUnixTime(flin,PDY,CYC)
    time[k]=tmp
    print(flin)
    print(time[k])

tindx = np.argsort(time)
time=time[tindx]
MT=MT[tindx]
F=F[tindx,:,:]

with nc.Dataset(flout, 'w', format='NETCDF4') as ncout:

    ncout.createDimension('X' , nx)
    ncout.createDimension('Y' , ny)
    ncout.createDimension('time', nt)

    lon_var=ncout.createVariable('longitude', 'f4', ('X','Y'))
    var=data["Longitude"]
    iutil.CopyAttributes(var, lon_var)
    lon_var[:,:]=X[:,:]

    lat_var=ncout.createVariable('latitude', 'f4', ('X','Y'))
    var=data["Latitude"]
    iutil.CopyAttributes(var, lat_var)
    lat_var[:,:]=Y[:,:]

    # Keep redundent time variables (time and MT) for conviniences
    time_var=ncout.createVariable('time', 'f8', ('time',))
    time_var.units         = 'seconds since 1970-01-01 00:00:00.0 0:00'
    time_var.long_name     = 'verification time generated by wgrib2 function verftime()'
    time_var.standard_name = 'time'
    time_var.axis          = 'T'
    time_var[:] = time[:]

    MT_var=ncout.createVariable("MT", 'f8', ('time',))
    var=data["MT"]
    iutil.CopyAttributes(var, MT_var)
    MT_var[:] = MT[:]

    f_var               = ncout.createVariable('ICEC_surface', 'f4', ('time','X','Y'),fill_value    = fill_value0)
    var=data["ice_coverage"]
    iutil.CopyAttributes(var, f_var)
    f_var[:,:,:]      = F[:,:,:]
