#!/bin/bash

######################################################################
# This job computes interpolation weights and distance to boundary for 
# a RWPS mesh. Currently configured for:
# nbm oc domain (wind)
# nbm ak domain (ice)
# rrfs hi domain (wind)
# rrfs pr domain (wind)
# rrfs ak domain (wind)
# rrfs conus domain (wind)
# rrfs na domain (wind)
# rtofs glo domain (surface currents, ice)
# stofs v3 (waterlevel, currents)
#
# Different sets of interpolation weights are created for rtofs ice 
# and surface currents so that ice concentration can be extrapolated
# by nearest node while currents are not extrapolated into coastal 
# regions outside of rtofs marine domain.
#
# Files are created in:
# /lfs/h2/emc/ptmp/$USER/RWPS.interpolation_weights.${meshID}"
######################################################################

cd ${DATA}
# Sample input directory dogwood
#SID="/lfs/h2/emc/couple/noscrub/keston.smith/SampleInput"
#PDY="20260730"
#cyc="00"

# Sample input directory cactus
SID="/lfs/h2/emc/couple/noscrub/keston.smith/SampleInputCactus"
PDY="20260921"
cyc="12"
Nprocs=32
######################################################################
# Compute rrfs interpolation weights for interpolating wind.
# no extrapolation for rrfs forecasts.
######################################################################
rrfs_hi=${SID}/wind.${PDY}.${cyc}/rrfs.${PDY}.${cyc}.wind10m.hi.nc
rrfs_pr=${SID}/wind.${PDY}.${cyc}/rrfs.${PDY}.${cyc}.wind10m.pr.nc
rrfs_ak=${SID}/wind.${PDY}.${cyc}/rrfs.${PDY}.${cyc}.wind10m.ak.nc
rrfs_na=${SID}/wind.${PDY}.${cyc}/rrfs.${PDY}.${cyc}.wind10m.na.nc
rrfs_conus=${SID}/wind.${PDY}.${cyc}/rrfs.${PDY}.${cyc}.wind10m.conus.nc


rrfsIntrp="${out}/InterpolationWeights.${meshname}.rrfs"
rrfsDst="${out}/DistToBndy.${meshname}.rrfs"

ushIW=${HOMErwps}/dev/compute_interpolation_weights/ush

rm -rf ${rrfsIntrp}.hi.nc ${rrfsDst}.hi.nc __pycache__
python ${ushIW}/compute_gridded_to_rwps_interp_weights.py $rrfs_hi ${mesh} ${rrfsIntrp}.hi.nc ${rrfsDst}.hi.nc -1

rm -rf ${rrfsIntrp}.pr.nc ${rrfsDst}.pr.nc __pycache__
python ${ushIW}/compute_gridded_to_rwps_interp_weights.py $rrfs_pr ${mesh} ${rrfsIntrp}.pr.nc ${rrfsDst}.pr.nc -1

rm -rf ${rrfsIntrp}.ak.nc ${rrfsDst}.ak.nc __pycache__
python ${ushIW}/compute_gridded_to_rwps_interp_weights.py $rrfs_ak ${mesh} ${rrfsIntrp}.ak.nc ${rrfsDst}.ak.nc -1

rm -rf ${rrfsIntrp}.na.nc ${rrfsDst}.na.nc __pycache__
python ${ushIW}/compute_gridded_to_rwps_interp_weights.py $rrfs_na ${mesh} ${rrfsIntrp}.na.nc ${rrfsDst}.na.nc -1

rm -rf ${rrfsIntrp}.conus.nc ${rrfsDst}.conus.nc __pycache__
python ${ushIW}/compute_gridded_to_rwps_interp_weights.py $rrfs_conus ${mesh} ${rrfsIntrp}.conus.nc ${rrfsDst}.conus.nc -1

######################################################################
# Compute nbm interpolation weights on oc domain for interpolating wind.
# Extrapolate to cover minor edge differences on south and east boundaries.
######################################################################
nbm_oc=${SID}/wind.${PDY}.${cyc}/nbm.${PDY}.${cyc}.wind10m.oc.nc
nbmIntrp="${out}/InterpolationWeights.${meshname}.nbm"
nbmDst="${out}/DistToBndy.${meshname}.nbm"

#extrapolate nbm oc wind to all points
rm ${nbmIntrp}.oc.nc ${nbmDst}.oc.nc
python ${ushIW}/compute_gridded_to_rwps_interp_weights.py $nbm_oc ${mesh} ${nbmIntrp}.oc.nc ${nbmDst}.oc.nc 1

######################################################################
# Compute nbm interpolation weights on ak domain for interpolating ice.
# No extrapolation outside the ak region
######################################################################
nbm_ak=${SID}/ice.${PDY}.${cyc}/nbm.${PDY}.${cyc}.ice.ak.nc
#do not extrapolate for NBM .ak. domain
rm ${nbmIntrp}.ak.nc ${nbmDst}.ak.nc
python ${ushIW}/compute_gridded_to_rwps_interp_weights.py $nbm_ak ${mesh} ${nbmIntrp}.ak.nc ${nbmDst}.ak.nc -1


######################################################################
# Compute rtofs interpolation weights for interpolating ice.
# Do extrapolate rtofs .glo. for full ice coverage in near shore.
######################################################################
rtofs_ice=${SID}/ice.${PDY}.${cyc}/rtofs.ice.${PDY}.nc
rtofsIntrp="${out}/InterpolationWeights.${meshname}.rtofs"
rtofsDst="${out}/DistToBndy.${meshname}.rtofs"
rm ${rtofsIntrp}.ice.nc ${rtofsDst}.ice.nc 
python ${ushIW}/compute_gridded_to_rwps_interp_weights.py ${rtofs_ice} ${mesh} ${rtofsIntrp}.ice.nc ${rtofsDst}.ice.nc 1 


######################################################################
# Compute rtofs interpolation weights for interpolating currents.
# Do not extrapolate into coastal regions
######################################################################
rtofs_cur=${SID}/rtofs.${PDY}/currents.${PDY}.rtofs.nc
#do not extrapolate rtofs global currents to near shore regions 
rm $rtofsIntrp.current.nc ${rtofsDst}.current.nc
python ${ushIW}/compute_gridded_to_rwps_interp_weights.py ${rtofs_cur} ${mesh} ${rtofsIntrp}.current.nc ${rtofsDst}.current.nc -1 


######################################################################
# Compute stofs interpolation weights for stofs v3 output
# All dates after ~ August 18 2026
# This is the same mesh geometry as stofs v2 so these will work for
# earlier forecasts as well. 
######################################################################
cd ${DATA}
stofs_glo="${SID}/stofs.20260921.12/stofs_2d_glo.t12z.fields.cwl.nc"

mkdir -p  ${DATA}/STOFSInterpWeights.${meshname}

# First construct parallel jobscript to compute weights using Nprocs division of destination domain(meshfile)
python ${ushIW}/compute_unstr_to_rwps_interp_weights.py ${stofs_glo} ${mesh} ${Nprocs}

# Now run the parallel job script written to work directory($DATA)
qsub -V -W block=true ${DATA}/jobcardcompute_unstr_to_rwps_interp_weightsPBS
wait

# combine text file output of parallel jobs
cat ${DATA}/STOFSInterpWeights.${meshname}/Part.IntrpWghts.*.txt > InterpWeights.${meshname}.stofs.txt

# sort order of nodes and convert output weights to netcdf file 
python ${ushIW}/convert_weights_to_netcdf.py ${stofs_glo} ${mesh} InterpWeights.${meshname}.stofs.txt 1
mv ${DATA}/InterpWeights.${meshname}.stofs.nc ${out}/InterpolationWeights.${meshname}.stofs.nc
mv ${DATA}/DistToBndy.${meshname}.stofs.nc ${out}/DistToBndy.${meshname}.stofs.nc

